apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-webapp
  labels:
    app: gitops-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-demo
  template:
    metadata:
      labels:
        app: gitops-demo
    spec:
      containers:
      - name: nginx
        image: nginx:latest  # De container image die ArgoCD moet deployen
        ports:
        - containerPort: 80
