apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-webapp
  labels:
    app: gitops-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-demo
  template:
    metadata:
      labels:
        app: gitops-demo
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:           # <<< ESSENTIEEL VOOR AUTOSCALING
          requests:
            cpu: "100m"      # 100 millicpu aangevraagd
