apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: webapp-cpu-scaler
  namespace: default # De namespace waar de webapp draait (standaard: 'default')
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gitops-webapp # De naam van de Deployment
  minReplicaCount: 1     # Minimum 1 replica
  maxReplicaCount: 5     # Maximum 5 replica's
  pollingInterval: 30    # KEDA controleert metrics elke 30 seconden
  triggers:
  - type: cpu
    metadata:
      # Doel: Schaal wanneer het gemiddelde CPU-gebruik 70% van de requested CPU (100m) bereikt.
      value: "70"
